[package]
name = "wordcount"
version = "0.1.0"
authors = ["michael <mchlstckl@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
regex = "1"
lazy_static = "1.2.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench_count_words"
harness = false